name: Salesforce CI

on:
  workflow_dispatch:

jobs:
  validate-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repository
        run: |
          pwd
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Check Salesforce CLI
        run: sf version

      - name: Validate Salesforce project
        run: |
          test -f sfdx-project.json
          echo "Salesforce DX project detected"